### ISSUE TITLE
OSX build failing

### ISSUE THREAD

**Issue by pelson** [conda-forge/matplotlib-feedstock#10]
https://travis-ci.org/conda-forge/matplotlib-feedstock/jobs/114864238

https://github.com/conda-forge/matplotlib-feedstock/pull/9#issuecomment-202030060

```
===== testing package: matplotlib-1.5.1-np110py27_0 =====
import: 'matplotlib'
import: 'matplotlib.pyplot'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 28, in <module>
    import matplotlib.pyplot
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import ft2font
ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: libfreetype.6.dylib
  Referenced from: /Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/matplotlib/ft2font.so
  Reason: image not found
```

**Comment by ocefpaf** [comment]
Fixed in #14. (All we need was `pkg-config`.)
