### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by jschueller** [conda-forge/matplotlib-feedstock#114]
hello,
The last commit here fails with this error on windows, and I get the same error on recipes matplotlib (pyfmi, assimulo, pyagrum)
Maybe a conda-build: 2.1.4 -> 2.1.6 issue.
The error can only be seen for py3 here, because we encounter also https://github.com/conda/conda-build/issues/1853.
```
(C:\bld\matplotlib_1489578580462\_t_env) C:\bld\matplotlib_1489578580462\test_tmp>"C:\bld\matplotlib_1489578580462\_t_env\python.exe" -s "C:\bld\matplotlib_1489578580462\test_tmp\run_test.py" 
import: 'matplotlib'
Traceback (most recent call last):
  File "C:\bld\matplotlib_1489578580462\test_tmp\run_test.py", line 2, in <module>
    import matplotlib
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 1182, in <module>
    rcParams = rc_params()
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 1015, in rc_params
    fname = matplotlib_fname()
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 825, in matplotlib_fname
    configdir = _get_configdir()
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 680, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 657, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\site-packages\matplotlib\__init__.py", line 583, in _create_tmp_config_dir
    username = getpass.getuser()
  File "C:\bld\matplotlib_1489578580462\_t_env\lib\getpass.py", line 169, in getuser
    import pwd
ModuleNotFoundError: No module named 'pwd'
(C:\bld\matplotlib_1489578580462\_t_env) C:\bld\matplotlib_1489578580462\test_tmp>if errorlevel 1 exit 1 
```

**Comment by jschueller** [comment]
edit: the error we see for python2 is different and similar to:
https://ci.appveyor.com/project/conda-forge/pyside-feedstock/build/1.0.54/job/9t9h9ym79jy4qway

**Comment by jschueller** [comment]
oh, the diff between the 2 is conda-build: 2.1.4 -> 2.1.6

**Comment by jschueller** [comment]
the python2 issue is due to:
https://github.com/conda/conda-build/issues/188

**Comment by ivoflipse** [comment]
I'm seeing this issue as well, trying to build a package that uses matplotlib

**Comment by jschueller** [comment]
It seems the error disappeared (see assimulo feedstock), but I guess this has to do with the pinning of conda-build to 2.1.4.
