### ISSUE TITLE
Python 3.8 & Matplotlib fails to import

### ISSUE THREAD

**Issue by milljm** [conda-forge/matplotlib-feedstock#410]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

When installing the following environment on Linux:
```bash
conda create -n testing python=3.8 matplotlib-base
conda activate testing
python3
```
One cannot import matplotlib:
```python
Python 3.8.20 | packaged by conda-forge | (default, Sep 30 2024, 17:52:49) 
[GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/matplotlib/__init__.py", line 129, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/matplotlib/_fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/pyparsing/__init__.py", line 129, in <module>
    from .util import *
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/pyparsing/util.py", line 14, in <module>
    class __config_flags:
  File "/data/milljm/host_conda/envs/testing/lib/python3.8/site-packages/pyparsing/util.py", line 17, in __config_flags
    _all_names: list[str] = []
TypeError: 'type' object is not subscriptable
```

### Installed packages

$ conda list
# packages in environment at /data/milljm/host_conda/envs/testing:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
astroid                   3.2.4            py38h578d9bd_0    conda-forge
atk-1.0                   2.38.0               h04ea711_2    conda-forge
aws-c-auth                0.7.31               h57bd9a3_0    conda-forge
aws-c-cal                 0.7.4                hfd43aa1_1    conda-forge
aws-c-common              0.9.28               hb9d3cd8_0    conda-forge
aws-c-compression         0.2.19               h756ea98_1    conda-forge
aws-c-event-stream        0.4.3                h29ce20c_2    conda-forge
aws-c-http                0.8.10               h5e77a74_0    conda-forge
aws-c-io                  0.14.18             h2af50b2_12    conda-forge
aws-c-mqtt                0.10.7               h02abb05_0    conda-forge
aws-c-s3                  0.6.6                h834ce55_0    conda-forge
aws-c-sdkutils            0.1.19               h756ea98_3    conda-forge
aws-checksums             0.1.20               h756ea98_0    conda-forge
aws-crt-cpp               0.28.3               h3e6eb3e_6    conda-forge
aws-sdk-cpp               1.11.407             h9f1560d_0    conda-forge
azure-core-cpp            1.14.0               h5cfcd09_0    conda-forge
azure-identity-cpp        1.10.0               h113e628_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h3cf044e_1    conda-forge
azure-storage-common-cpp  12.8.0               h736e048_1    conda-forge
azure-storage-files-datalake-cpp 12.12.0              ha633028_1    conda-forge
bcrypt                    4.2.0            py38h4005ec7_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
brotli-python             1.0.9            py38hfa26641_8    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.1               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.0           py38heb5c249_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
clang-format              16.0.6          default_hb5137d0_13    conda-forge
clang-format-16           16.0.6          default_hb5137d0_13    conda-forge
clang-tools               16.0.6          default_hb5137d0_13    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
cpython                   3.8.20           py38hd8ed1ab_2    conda-forge
cryptography              43.0.0           py38hf793753_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.3           py38h01eb140_0    conda-forge
dask-core                 2023.5.0           pyhd8ed1ab_0    conda-forge
deepdiff                  8.0.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.9              pyhd8ed1ab_0    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1           py38h2019614_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fsspec                    2024.9.0           pyhff2d567_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.12              hb9ae30d_0    conda-forge
gflags                    2.2.2             h5888daf_1005    conda-forge
git-lfs                   3.5.1                ha770c72_0    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5            py38h6a1700d_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
graphviz                  12.0.0               hba01fac_0    conda-forge
gtk2                      2.24.33              h6470451_5    conda-forge
gts                       0.7.6                h977cf35_4    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py38h55b5aab_102    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imagecodecs-lite          2019.12.3        py38he82f83a_8    conda-forge
imageio                   2.36.0             pyh12aca89_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib-resources       6.4.5              pyhd8ed1ab_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
isort                     5.13.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lazy-loader               0.4                pyhd8ed1ab_1    conda-forge
lazy_loader               0.4                pyhd8ed1ab_1    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarrow                  17.0.0          ha07344c_22_cpu    conda-forge
libarrow-acero            17.0.0          h5888daf_22_cpu    conda-forge
libarrow-dataset          17.0.0          h5888daf_22_cpu    conda-forge
libarrow-substrait        17.0.0          he882d9a_22_cpu    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libclang-cpp16            16.0.6          default_hb5137d0_13    conda-forge
libclang13                19.1.1          default_h9c6a7e4_0    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgd                     2.3.3               hd3e95f3_10    conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libglib                   2.82.1               h2ff4ddf_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libgoogle-cloud           2.30.0               h438788a_0    conda-forge
libgoogle-cloud-storage   2.30.0               h0121fbd_0    conda-forge
libgrpc                   1.65.5               hf5c653b_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libllvm16                 16.0.6               hb3ce162_3    conda-forge
libllvm19                 19.1.1               ha7bfdaf_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libparquet                17.0.0          h6bd9018_22_cpu    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     16.4                 h2d7952a_2    conda-forge
libprotobuf               5.27.5               h5b01275_2    conda-forge
libre2-11                 2023.11.01           hbbce691_0    conda-forge
librsvg                   2.58.4               hc0ffecb_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libthrift                 0.21.0               h0e7cc3e_0    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
livereload                2.7.0              pyhd8ed1ab_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      5.3.0            py38hd8ce619_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
mako                      1.3.5              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5            py38h01eb140_0    conda-forge
matplotlib-base           3.7.3            py38h58ed7fa_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mock                      5.1.0              pyhd8ed1ab_0    conda-forge
moose-tools               2024.10.01       py38hd7414a4_0    local
mpc                       1.3.1                h24ddda3_1    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
orc                       2.0.2                h690cf93_1    conda-forge
orderly-set               5.2.2              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3            py38h01efb38_1    conda-forge
pango                     1.54.0               h4c5309f_1    conda-forge
paramiko                  3.5.0              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    10.4.0           py38h2bc05a7_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
psycopg2                  2.9.9            py38hdc7b9b0_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pyarrow                   17.0.0           py38hb563948_1    conda-forge
pyarrow-core              17.0.0          py38h7debecc_1_cpu    conda-forge
pybtex                    0.24.0             pyhd8ed1ab_2    conda-forge
pycobertura               3.3.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pylatexenc                2.10               pyhd8ed1ab_0    conda-forge
pylint                    3.2.7              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py38h01eb140_3    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.20          h4a871b0_2_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      5_cp38    conda-forge
pytz                      2024.2             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1            py38h7f0c24c_1    conda-forge
pyyaml                    6.0.2            py38h2019614_0    conda-forge
re2                       2023.11.01           h77b4e00_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6           py38h01eb140_0    conda-forge
ruamel.yaml.clib          0.2.8            py38h01eb140_0    conda-forge
s2n                       1.5.5                h3931f03_0    conda-forge
scikit-image              0.20.0           py38hf403d1e_1    conda-forge
scipy                     1.9.1            py38hea3f02b_0    conda-forge
setuptools                59.8.0           py38h578d9bd_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sympy                     1.13.3           pyh2585a3b_104    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tifffile                  2020.6.3                   py_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
tomlkit                   0.13.2             pyha770c72_0    conda-forge
toolz                     1.0.0              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1            py38hfb59056_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
uncertainties             3.2.2              pyhd8ed1ab_1    conda-forge
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0           py38h62bed22_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

### Environment info

$ conda info --all

     active environment : testing
    active env location : /data/milljm/host_conda/envs/testing
            shell level : 2
       user config file : /home/milljm/.condarc
 populated config files : /data/milljm/host_conda/.condarc
                          /home/milljm/.condarc
          conda version : 24.9.1
    conda-build version : 24.7.1
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen4
                          __conda=24.9.1=0
                          __cuda=12.4=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /data/milljm/host_conda  (writable)
      conda av data dir : /data/milljm/host_conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.software.inl.gov/public/linux-64
                          https://conda.software.inl.gov/public/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /data/milljm/host_conda/pkgs
                          /home/milljm/.conda/pkgs
       envs directories : /data/milljm/host_conda/envs
                          /home/milljm/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.1 requests/2.31.0 CPython/3.10.14 Linux/4.18.0-553.16.1.el8_10.x86_64 rocky/8.10 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 11270:11270
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /data/milljm/host_conda
compilers                /data/milljm/host_conda/envs/compilers
testing               *  /data/milljm/host_conda/envs/testing

sys.version: 3.10.14 | packaged by conda-forge | (mai...
sys.prefix: /data/milljm/host_conda
sys.executable: /data/milljm/host_conda/bin/python
conda location: /data/milljm/host_conda/lib/python3.10/site-packages/conda
conda-build: /data/milljm/host_conda/bin/conda-build
conda-convert: /data/milljm/host_conda/bin/conda-convert
conda-debug: /data/milljm/host_conda/bin/conda-debug
conda-develop: /data/milljm/host_conda/bin/conda-develop
conda-env: /data/milljm/host_conda/bin/conda-env
conda-inspect: /data/milljm/host_conda/bin/conda-inspect
conda-metapackage: /data/milljm/host_conda/bin/conda-metapackage
conda-render: /data/milljm/host_conda/bin/conda-render
conda-skeleton: /data/milljm/host_conda/bin/conda-skeleton
user site dirs: ~/.local/lib/python3.7
                ~/.local/lib/python2.7
                ~/.local/lib/python3.11

CIO_TEST: <not set>
CONDA_ALLOW_SOFTLINKS: false
CONDA_DEFAULT_ENV: testing
CONDA_EXE: /data/milljm/host_conda/bin/conda
CONDA_PREFIX: /data/milljm/host_conda/envs/testing
CONDA_PREFIX_1: /data/milljm/host_conda
CONDA_PROMPT_MODIFIER: 
CONDA_PYTHON_EXE: /data/milljm/host_conda/bin/python
CONDA_ROOT: /data/milljm/host_conda
CONDA_SHLVL: 2
CURL_CA_BUNDLE: <not set>
CUSTOM_PATH: /data/milljm/host_conda
FPATH: /usr/local/lmod/lmod/init/ksh_funcs
LD_PRELOAD: <not set>
MANPATH: /usr/local/lmod/lmod/share/man:
MODULEPATH: NONE/modulefiles/Linux:NONE/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core
PATH: /data/milljm/host_conda/envs/testing/bin:/data/milljm/host_conda/condabin:/home/milljm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

**Comment by milljm** [comment]
Oh... Python 3.8 only just reached EOL. I love to hear... less I have to suppose. Closing!
