### ISSUE TITLE
libpng failure on Linux

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/matplotlib-feedstock#62]
I'm having issues with the libpng version on Linux:

```
$ conda create -n test-png -c conda-forge matplotlib python 
Fetching package metadata: ......
Solving package specifications: .................................
Package plan for installation in environment /disk1/data/anaconda/envs/test-png:

The following NEW packages will be INSTALLED:

    cairo:           1.12.18-8        
    cycler:          0.10.0-py27_0    
    fontconfig:      2.11.1-3         
    freetype:        2.6.3-1          
    functools32:     3.2.3.2-py27_1   
    gettext:         0.19.7-1         
    glib:            2.48.0-4         
    harfbuzz:        1.0.6-0          
    icu:             56.1-4           
    libffi:          3.2.1-2          
    libiconv:        1.14-3           
    libpng:          1.6.24-0         
    libxml2:         2.9.4-0          
    matplotlib:      1.5.3-np111py27_0
    mkl:             11.3.3-0         
    ncurses:         5.9-9            
    numpy:           1.11.1-py27_0    
    openssl:         1.0.2j-0         
    pango:           1.40.1-0         
    pcre:            8.39-0           
    pip:             8.1.2-py27_0     
    pixman:          0.32.6-0         
    pyparsing:       2.1.8-py27_0     
    pyqt:            4.11.4-py27_4    
    python:          2.7.12-1         
    python-dateutil: 2.5.3-py27_0     
    pytz:            2016.6.1-py27_0  
    qt:              4.8.7-4          
    readline:        6.2-2            
    setuptools:      27.2.0-py27_0    
    sip:             4.18-py27_0      
    six:             1.10.0-py27_0    
    sqlite:          3.13.0-1         
    tk:              8.5.19-0         
    wheel:           0.29.0-py27_0    
    xz:              5.2.2-0          
    zlib:            1.2.8-3          

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#########################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test-png
#
# To deactivate this environment, use:
# $ source deactivate
#
$ source activate test-png
pythondiscarding /disk1/data/anaconda/envs/hyperion-0.9.8/bin from PATH
 prepending /disk1/data/anaconda/envs/test-png/bin to PATH
$ python -c 'import matplotlib.pyplot'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/disk1/data/anaconda/envs/test-png/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libpng15.so.15: cannot open shared object file: No such file or directory
```

**Comment by astrofrog** [comment]
I was using an old version of conda (this was on an old machine) - all works fine now, sorry for the noise!
